export const PAGES = {
  HOME: "/",
  PRIVACY: "/privacy",
  REGISTER: "/auth/register",
  LOGIN: "/auth/login",
  ADMIN_DASHBOARD: "/admin",
  ADMIN_EVENTS: "/admin/events",
  ADMIN_ACTIVE_EVENTS: "/admin/active-events",
  ADMIN_VOLUNTEERS: "/admin/volunteers",
  ADMIN_ORGANIZER_REQUESTS: "/admin/organizer-requests",
  ORGANIZER_DASHBOARD: "/organizer/dashboard",
  VOLUNTEER_DASHBOARD: "/volunteer/dashboard",
  ORGANIZER_EVENTS: "/organizer/events",
  VOLUNTEER_EVENTS: "/volunteer/events",
  VOLUNTEER_APPLICATIONS: "/volunteer/applications",
  VOLUNTEER_ATTENDED_EVENTS: "/volunteer/events/attended",
  ORGANIZER_REPORTS: "/organizer/reports",
  VOLUNTEER_REPORTS: "/volunteer/reports",
  EDIT_EVENT: (eventId: string) => `/organizer/events/${eventId}/edit`,
  VOLUNTEER_EVENT: (eventId: string) => `/volunteer/events/${eventId}`,
};
